version: '3.3'
services:   

    eureka:
        image: eureka
         
       
        deploy:
            replicas: 1     
        ports:
            - '8761:8761'
        networks:
            - stackone            
    unicorn:
        image: unicorn
             
        deploy:
            replicas: 2    
        depends_on:
            - eureka
           
       
          
        ports:
            - '2030:2030'
        networks:
            - stackone
            
            
    hacker:
        image: hacker
              
       
        deploy:
            replicas: 1    
        depends_on:
            - eureka           
             
        ports:
            - '2020:2020'
        networks:
            - stackone
            
            
networks:
    stackone:
        driver: overlay
